import 'models.dart';

/// Built-in exercise library. IDs are stable and referenced by plans and
/// logs. Names, steps, and tips are seed data, kept out of the ARB files.
const List<Exercise> exerciseLibrary = [
  // ----- Chest -----
  Exercise(
    id: 'benchPress',
    name: 'Barbell Bench Press',
    group: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    isCompound: true,
    steps: [
      'Lie on the bench with your eyes under the bar, feet flat on the floor.',
      'Grip the bar slightly wider than shoulder width and unrack it over your chest.',
      'Lower the bar under control to your mid chest, elbows about 45 degrees from your body.',
      'Press the bar back up until your arms are straight.',
    ],
    tips: [
      'Keep your shoulder blades pinched together on the bench.',
      'Touch your chest lightly, never bounce the bar.',
      'Use a spotter or safety pins when going heavy.',
    ],
  ),
  Exercise(
    id: 'inclineBenchPress',
    name: 'Incline Barbell Press',
    group: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    isCompound: true,
    steps: [
      'Set the bench to a 30 to 45 degree incline.',
      'Grip the bar slightly wider than shoulder width and unrack it.',
      'Lower the bar to your upper chest under control.',
      'Press back up until your arms are straight.',
    ],
    tips: [
      'A steeper incline shifts work to the shoulders, stay near 30 degrees.',
      'Keep your butt on the bench the whole set.',
    ],
  ),
  Exercise(
    id: 'dbBenchPress',
    name: 'Dumbbell Bench Press',
    group: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    isCompound: true,
    steps: [
      'Sit on the bench with a dumbbell on each thigh, then lie back kicking them to your chest.',
      'Start with the dumbbells over your chest, palms facing forward.',
      'Lower them out and down until your elbows pass bench level.',
      'Press back up and slightly together at the top.',
    ],
    tips: [
      'Dumbbells allow a deeper stretch than the bar, use it under control.',
      'Do not let the dumbbells drift toward your face.',
    ],
  ),
  Exercise(
    id: 'inclineDbPress',
    name: 'Incline Dumbbell Press',
    group: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    isCompound: true,
    steps: [
      'Set the bench to a 30 degree incline and sit with dumbbells on your thighs.',
      'Lie back and press the dumbbells over your upper chest.',
      'Lower slowly until you feel a stretch across your chest.',
      'Press back up without locking the elbows harshly.',
    ],
    tips: [
      'Keep your wrists stacked straight over your elbows.',
      'Lower for a slow two count on every rep.',
    ],
  ),
  Exercise(
    id: 'chestFly',
    name: 'Cable Chest Fly',
    group: 'chest',
    equipment: 'cable',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    steps: [
      'Set both pulleys at chest height and grab a handle in each hand.',
      'Step forward into a split stance with a slight bend in your elbows.',
      'Bring your hands together in a wide arc in front of your chest.',
      'Return slowly until you feel a stretch in your chest.',
    ],
    tips: [
      'Keep the same elbow bend the whole rep, this is a hug, not a press.',
      'Squeeze your chest for a second when your hands meet.',
    ],
  ),
  Exercise(
    id: 'pecDeck',
    name: 'Pec Deck Machine',
    group: 'chest',
    equipment: 'machine',
    primaryMuscles: ['chest'],
    steps: [
      'Adjust the seat so the handles sit at chest height.',
      'Sit tall with your back flat against the pad.',
      'Bring the handles together in front of you.',
      'Open back up slowly to a comfortable stretch.',
    ],
    tips: [
      'Do not let the weight stack slam between reps.',
      'Great as a finisher after pressing work.',
    ],
  ),
  Exercise(
    id: 'pushUp',
    name: 'Push-Up',
    group: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps', 'abs'],
    isCompound: true,
    steps: [
      'Place your hands slightly wider than shoulder width on the floor.',
      'Form a straight line from head to heels.',
      'Lower your chest to just above the floor.',
      'Push back up until your arms are straight.',
    ],
    tips: [
      'Squeeze your glutes and abs so your hips never sag.',
      'Too easy? Elevate your feet or add a pause at the bottom.',
    ],
  ),
  Exercise(
    id: 'chestDip',
    name: 'Chest Dip',
    group: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    isCompound: true,
    steps: [
      'Grab the parallel bars and press up to straight arms.',
      'Lean your torso slightly forward.',
      'Lower until your upper arms are about parallel to the floor.',
      'Press back up without locking out hard.',
    ],
    tips: [
      'The forward lean is what targets the chest over the triceps.',
      'Stop the descent if you feel pinching in the front of the shoulder.',
    ],
  ),

  // ----- Back -----
  Exercise(
    id: 'deadlift',
    name: 'Deadlift',
    group: 'back',
    equipment: 'barbell',
    primaryMuscles: ['lowerBack', 'glutes', 'hamstrings'],
    secondaryMuscles: ['lats', 'traps', 'forearms', 'quads'],
    isCompound: true,
    steps: [
      'Stand with the bar over your mid foot, feet hip width apart.',
      'Hinge down and grip the bar just outside your legs.',
      'Brace your core, flatten your back, and pull your chest up.',
      'Drive through your legs and stand up tall, keeping the bar close.',
      'Push your hips back and lower the bar under control.',
    ],
    tips: [
      'The bar should brush your legs the entire way up and down.',
      'Never round your lower back, reset your brace before every rep.',
      'This is the lift where form matters most, film yourself or ask for a check.',
    ],
  ),
  Exercise(
    id: 'pullUp',
    name: 'Pull-Up',
    group: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upperBack', 'forearms'],
    isCompound: true,
    steps: [
      'Hang from the bar with an overhand grip slightly wider than shoulders.',
      'Pull your shoulder blades down, then pull your chin over the bar.',
      'Lower yourself all the way to straight arms.',
    ],
    tips: [
      'Think about driving your elbows down to your hips.',
      'Use the assisted machine or a band if you cannot do 5 clean reps yet.',
    ],
  ),
  Exercise(
    id: 'chinUp',
    name: 'Chin-Up',
    group: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['upperBack', 'forearms'],
    isCompound: true,
    steps: [
      'Hang from the bar with an underhand grip at shoulder width.',
      'Pull your chin over the bar, leading with your chest.',
      'Lower under control to a full hang.',
    ],
    tips: [
      'The underhand grip brings the biceps in, expect to be a bit stronger than pull-ups.',
      'Avoid swinging, keep your core tight.',
    ],
  ),
  Exercise(
    id: 'latPulldown',
    name: 'Lat Pulldown',
    group: 'back',
    equipment: 'cable',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upperBack'],
    isCompound: true,
    steps: [
      'Sit with your thighs secured under the pads.',
      'Grip the bar wider than shoulder width.',
      'Pull the bar down to your upper chest while leaning back slightly.',
      'Let the bar rise slowly to full arm extension.',
    ],
    tips: [
      'Pull with your elbows, not your hands.',
      'Do not pull the bar behind your neck.',
    ],
  ),
  Exercise(
    id: 'barbellRow',
    name: 'Barbell Row',
    group: 'back',
    equipment: 'barbell',
    primaryMuscles: ['upperBack', 'lats'],
    secondaryMuscles: ['biceps', 'lowerBack', 'forearms'],
    isCompound: true,
    steps: [
      'Hinge forward until your torso is about 45 degrees, knees soft.',
      'Grip the bar shoulder width, arms hanging straight.',
      'Row the bar to your lower ribs.',
      'Lower under control without dropping your chest.',
    ],
    tips: [
      'Keep your back flat, brace like the deadlift.',
      'If you have to heave with your hips, the bar is too heavy.',
    ],
  ),
  Exercise(
    id: 'dbRow',
    name: 'One-Arm Dumbbell Row',
    group: 'back',
    equipment: 'dumbbell',
    primaryMuscles: ['lats', 'upperBack'],
    secondaryMuscles: ['biceps', 'forearms'],
    isCompound: true,
    steps: [
      'Place one knee and the same-side hand on a bench.',
      'Hold the dumbbell in the other hand, arm hanging straight.',
      'Row the dumbbell to your hip, keeping your torso still.',
      'Lower to a full stretch and repeat, then switch sides.',
    ],
    tips: [
      'Row to the hip, not the shoulder, to keep the lats working.',
      'Do not rotate your torso to lift more weight.',
    ],
  ),
  Exercise(
    id: 'seatedRow',
    name: 'Seated Cable Row',
    group: 'back',
    equipment: 'cable',
    primaryMuscles: ['upperBack', 'lats'],
    secondaryMuscles: ['biceps'],
    isCompound: true,
    steps: [
      'Sit with your feet on the platform, knees slightly bent.',
      'Grab the handle with a neutral grip, back upright.',
      'Pull the handle to your stomach, squeezing your shoulder blades.',
      'Let your arms extend fully without rounding forward.',
    ],
    tips: [
      'Chest stays tall the whole set.',
      'Pause for one second at your stomach on every rep.',
    ],
  ),
  Exercise(
    id: 'tBarRow',
    name: 'T-Bar Row',
    group: 'back',
    equipment: 'barbell',
    primaryMuscles: ['upperBack', 'lats'],
    secondaryMuscles: ['biceps', 'lowerBack'],
    isCompound: true,
    steps: [
      'Straddle the bar and grip the handles with a flat back.',
      'Keep your torso near 45 degrees.',
      'Row the weight to your chest.',
      'Lower slowly to a full stretch.',
    ],
    tips: [
      'Smaller plates give a longer range of motion.',
      'Do not stand up as you fatigue, keep the hinge.',
    ],
  ),
  Exercise(
    id: 'straightArmPulldown',
    name: 'Straight-Arm Pulldown',
    group: 'back',
    equipment: 'cable',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['triceps', 'abs'],
    steps: [
      'Stand facing a high pulley holding the bar with straight arms.',
      'Hinge slightly forward with a tight core.',
      'Sweep the bar down to your thighs in an arc.',
      'Return slowly until your arms are overhead.',
    ],
    tips: [
      'Elbows stay almost straight, all motion comes from the shoulders.',
      'Feel the stretch in your lats at the top of every rep.',
    ],
  ),
  Exercise(
    id: 'backExtension',
    name: 'Back Extension',
    group: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['lowerBack', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    steps: [
      'Set the pad just below your hip bones and hook your feet in.',
      'Cross your arms over your chest.',
      'Lower your torso until you feel a hamstring stretch.',
      'Raise back up until your body forms a straight line.',
    ],
    tips: [
      'Do not hyperextend past straight at the top.',
      'Hold a plate against your chest to add load.',
    ],
  ),
  Exercise(
    id: 'shrug',
    name: 'Dumbbell Shrug',
    group: 'back',
    equipment: 'dumbbell',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['forearms'],
    steps: [
      'Stand tall holding a heavy dumbbell in each hand.',
      'Shrug your shoulders straight up toward your ears.',
      'Hold the top for a second, then lower slowly.',
    ],
    tips: [
      'Straight up and down, do not roll the shoulders.',
      'Keep your arms relaxed, the traps do the lifting.',
    ],
  ),

  // ----- Shoulders -----
  Exercise(
    id: 'overheadPress',
    name: 'Overhead Press',
    group: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'traps', 'abs'],
    isCompound: true,
    steps: [
      'Hold the bar at shoulder height, hands just outside shoulders.',
      'Brace your core and squeeze your glutes.',
      'Press the bar straight overhead, moving your head back slightly.',
      'Finish with the bar over your mid foot, then lower to your shoulders.',
    ],
    tips: [
      'Do not lean back to grind out reps, that turns it into an incline press.',
      'Keep your wrists straight and elbows under the bar.',
    ],
  ),
  Exercise(
    id: 'dbShoulderPress',
    name: 'Seated Dumbbell Press',
    group: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'traps'],
    isCompound: true,
    steps: [
      'Sit on an upright bench with a dumbbell at each shoulder.',
      'Press both dumbbells overhead until your arms are straight.',
      'Lower under control back to shoulder height.',
    ],
    tips: [
      'Keep your lower back against the pad, do not arch hard.',
      'Lower until your elbows reach about 90 degrees.',
    ],
  ),
  Exercise(
    id: 'arnoldPress',
    name: 'Arnold Press',
    group: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    steps: [
      'Sit holding the dumbbells at shoulder height, palms facing you.',
      'Press up while rotating your palms to face forward.',
      'Reverse the rotation on the way down.',
    ],
    tips: [
      'Use lighter weight than a normal press, the rotation is the point.',
      'Move smoothly, no jerking through the twist.',
    ],
  ),
  Exercise(
    id: 'lateralRaise',
    name: 'Dumbbell Lateral Raise',
    group: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['shoulders'],
    steps: [
      'Stand tall with a light dumbbell in each hand at your sides.',
      'Raise both arms out to the sides until they reach shoulder height.',
      'Lower slowly back to your sides.',
    ],
    tips: [
      'Lead with your elbows, pinkies slightly up, like pouring water.',
      'If you have to swing, the weight is too heavy. Go lighter.',
    ],
  ),
  Exercise(
    id: 'frontRaise',
    name: 'Dumbbell Front Raise',
    group: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['shoulders'],
    steps: [
      'Hold a dumbbell in each hand in front of your thighs.',
      'Raise one arm straight in front to shoulder height.',
      'Lower slowly and alternate arms.',
    ],
    tips: [
      'Keep a slight elbow bend and avoid rocking your torso.',
      'Skip it on heavy pressing days, the front delts are already worked.',
    ],
  ),
  Exercise(
    id: 'rearDeltFly',
    name: 'Rear Delt Fly',
    group: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['shoulders', 'upperBack'],
    steps: [
      'Hinge forward until your torso is near parallel with the floor.',
      'Let the dumbbells hang under your chest, palms facing each other.',
      'Raise both arms out to the sides, squeezing your shoulder blades.',
      'Lower slowly without standing up.',
    ],
    tips: [
      'Very light weight, very strict form.',
      'Think about pulling your hands apart, not lifting them up.',
    ],
  ),
  Exercise(
    id: 'facePull',
    name: 'Cable Face Pull',
    group: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['shoulders', 'upperBack'],
    secondaryMuscles: ['traps'],
    steps: [
      'Set a rope attachment at upper chest height.',
      'Grab the rope ends with thumbs pointing back.',
      'Pull the rope toward your face, splitting the ends past your ears.',
      'Return slowly with your shoulders down.',
    ],
    tips: [
      'Finish each rep with your elbows high and hands beside your head.',
      'The best insurance for healthy shoulders, do these every pull day.',
    ],
  ),
  Exercise(
    id: 'uprightRow',
    name: 'Cable Upright Row',
    group: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['shoulders', 'traps'],
    secondaryMuscles: ['biceps'],
    steps: [
      'Stand holding a straight bar on a low pulley, hands shoulder width.',
      'Pull the bar up along your body to chest height, elbows leading.',
      'Lower under control.',
    ],
    tips: [
      'Stop at chest height, pulling higher can pinch the shoulder.',
      'A wider grip is friendlier to the wrists and shoulders.',
    ],
  ),

  // ----- Arms -----
  Exercise(
    id: 'bicepCurl',
    name: 'Dumbbell Bicep Curl',
    group: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    steps: [
      'Stand with a dumbbell in each hand, palms facing forward.',
      'Curl both dumbbells up to shoulder height.',
      'Lower slowly all the way to straight arms.',
    ],
    tips: [
      'Pin your elbows to your sides, only the forearms move.',
      'The slow lowering builds as much muscle as the lift.',
    ],
  ),
  Exercise(
    id: 'barbellCurl',
    name: 'Barbell Curl',
    group: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    steps: [
      'Hold the bar at shoulder width, palms up.',
      'Curl the bar to your shoulders without moving your elbows.',
      'Lower under control to straight arms.',
    ],
    tips: [
      'No hip swing. If you must cheat, the bar is too heavy.',
      'An EZ-curl bar is easier on the wrists.',
    ],
  ),
  Exercise(
    id: 'hammerCurl',
    name: 'Hammer Curl',
    group: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['biceps', 'forearms'],
    steps: [
      'Hold the dumbbells at your sides with palms facing your body.',
      'Curl up keeping the neutral grip the whole way.',
      'Lower slowly.',
    ],
    tips: [
      'Builds the forearms and the thickness of the upper arm.',
      'Can be done alternating or both arms together.',
    ],
  ),
  Exercise(
    id: 'preacherCurl',
    name: 'Preacher Curl',
    group: 'arms',
    equipment: 'machine',
    primaryMuscles: ['biceps'],
    steps: [
      'Sit with the backs of your upper arms flat on the preacher pad.',
      'Curl the weight up toward your shoulders.',
      'Lower slowly until your arms are almost straight.',
    ],
    tips: [
      'Do not bounce out of the bottom, that strains the elbow.',
      'The pad removes cheating, expect to lift less than a standing curl.',
    ],
  ),
  Exercise(
    id: 'concentrationCurl',
    name: 'Concentration Curl',
    group: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['biceps'],
    steps: [
      'Sit on a bench, elbow braced against your inner thigh.',
      'Curl the dumbbell to your shoulder.',
      'Lower slowly to a full stretch.',
    ],
    tips: [
      'Watch the bicep work, focus improves the contraction.',
      'Strict and slow beats heavy and sloppy here.',
    ],
  ),
  Exercise(
    id: 'cableCurl',
    name: 'Cable Curl',
    group: 'arms',
    equipment: 'cable',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    steps: [
      'Attach a straight bar to the low pulley and grip palms up.',
      'Curl the bar to your shoulders, elbows pinned.',
      'Lower under control against the cable tension.',
    ],
    tips: [
      'The cable keeps tension at the bottom where dumbbells rest.',
      'Great as the last biceps exercise of the day.',
    ],
  ),
  Exercise(
    id: 'tricepPushdown',
    name: 'Tricep Rope Pushdown',
    group: 'arms',
    equipment: 'cable',
    primaryMuscles: ['triceps'],
    steps: [
      'Face a high pulley with a rope attachment, elbows at your sides.',
      'Push the rope down until your arms are straight, splitting the ends.',
      'Let the rope rise until your forearms pass parallel.',
    ],
    tips: [
      'Elbows stay glued to your ribs the entire set.',
      'Lean slightly forward but keep your back straight.',
    ],
  ),
  Exercise(
    id: 'skullCrusher',
    name: 'Skull Crusher',
    group: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['triceps'],
    steps: [
      'Lie on a bench holding the bar over your chest, narrow grip.',
      'Bend only at the elbows, lowering the bar toward your forehead.',
      'Extend back up to straight arms.',
    ],
    tips: [
      'Lower to the top of your head or just behind it, slowly.',
      'Drop the weight, not your guard. This one punishes sloppy form.',
    ],
  ),
  Exercise(
    id: 'overheadTricepExtension',
    name: 'Overhead Tricep Extension',
    group: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['triceps'],
    steps: [
      'Hold one dumbbell with both hands overhead.',
      'Lower it behind your head by bending the elbows.',
      'Extend back up to straight arms.',
    ],
    tips: [
      'Keep your elbows pointing forward, not flaring out.',
      'The overhead stretch hits the long head other extensions miss.',
    ],
  ),
  Exercise(
    id: 'closeGripBench',
    name: 'Close-Grip Bench Press',
    group: 'arms',
    equipment: 'barbell',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    isCompound: true,
    steps: [
      'Lie on the bench and grip the bar at shoulder width.',
      'Lower the bar to your lower chest, elbows close to your body.',
      'Press back up focusing on pushing with the triceps.',
    ],
    tips: [
      'Shoulder width, not hands touching. Too narrow hurts the wrists.',
      'The heaviest triceps builder you can do.',
    ],
  ),

  // ----- Legs -----
  Exercise(
    id: 'squat',
    name: 'Barbell Back Squat',
    group: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lowerBack', 'abs'],
    isCompound: true,
    steps: [
      'Rest the bar on your upper back and step out of the rack.',
      'Set your feet shoulder width, toes slightly out.',
      'Brace, then sit down between your legs until your thighs pass parallel.',
      'Drive back up through your whole foot.',
    ],
    tips: [
      'Knees track in line with your toes, never caving inward.',
      'Keep your whole foot planted, heels never rise.',
      'Depth first, weight second.',
    ],
  ),
  Exercise(
    id: 'frontSquat',
    name: 'Front Squat',
    group: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'abs', 'upperBack'],
    isCompound: true,
    steps: [
      'Rest the bar on your front shoulders, elbows high.',
      'Keep your torso as upright as possible.',
      'Squat down until your thighs pass parallel.',
      'Drive up keeping your elbows lifted.',
    ],
    tips: [
      'If your wrists are tight, use a cross-arm grip or straps.',
      'Elbows dropping means the weight is about to fall forward.',
    ],
  ),
  Exercise(
    id: 'gobletSquat',
    name: 'Goblet Squat',
    group: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs'],
    isCompound: true,
    steps: [
      'Hold a dumbbell vertically against your chest with both hands.',
      'Squat down between your knees, elbows inside your thighs.',
      'Stand back up tall.',
    ],
    tips: [
      'The best squat to learn depth and posture, perfect for beginners.',
      'Keep your chest tall against the counterweight.',
    ],
  ),
  Exercise(
    id: 'legPress',
    name: 'Leg Press',
    group: 'legs',
    equipment: 'machine',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    isCompound: true,
    steps: [
      'Sit in the machine with your feet shoulder width on the platform.',
      'Release the safeties and lower the platform toward your chest.',
      'Press back up without fully locking your knees.',
    ],
    tips: [
      'Never let your lower back curl off the pad at the bottom.',
      'Higher foot placement hits more glutes and hamstrings.',
    ],
  ),
  Exercise(
    id: 'hackSquat',
    name: 'Hack Squat',
    group: 'legs',
    equipment: 'machine',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    isCompound: true,
    steps: [
      'Position your shoulders under the pads, feet shoulder width.',
      'Release the handles and squat down until your thighs pass parallel.',
      'Drive back up through your whole foot.',
    ],
    tips: [
      'A lower foot placement emphasizes the quads more.',
      'Control the descent, do not dive-bomb into the bottom.',
    ],
  ),
  Exercise(
    id: 'romanianDeadlift',
    name: 'Romanian Deadlift',
    group: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lowerBack', 'forearms'],
    isCompound: true,
    steps: [
      'Hold the bar at your thighs, feet hip width.',
      'Push your hips straight back, sliding the bar down your legs.',
      'Stop when you feel a deep hamstring stretch, around mid shin.',
      'Drive your hips forward to stand tall.',
    ],
    tips: [
      'Knees stay softly bent, this is a hinge, not a squat.',
      'Flat back always. Shorten the range before you round.',
    ],
  ),
  Exercise(
    id: 'legCurl',
    name: 'Lying Leg Curl',
    group: 'legs',
    equipment: 'machine',
    primaryMuscles: ['hamstrings'],
    steps: [
      'Lie face down with the pad against your lower calves.',
      'Curl your heels toward your glutes.',
      'Lower slowly to straight legs.',
    ],
    tips: [
      'Keep your hips pressed into the bench the whole set.',
      'Pause for a second at the top of each rep.',
    ],
  ),
  Exercise(
    id: 'legExtension',
    name: 'Leg Extension',
    group: 'legs',
    equipment: 'machine',
    primaryMuscles: ['quads'],
    steps: [
      'Sit with the pad on your lower shins, knees lined up with the pivot.',
      'Extend your legs until they are straight.',
      'Lower slowly without letting the stack slam.',
    ],
    tips: [
      'Squeeze hard for a second at full extension.',
      'Moderate weight and clean reps, this is a finisher, not a max lift.',
    ],
  ),
  Exercise(
    id: 'lunge',
    name: 'Walking Lunge',
    group: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    isCompound: true,
    steps: [
      'Hold a dumbbell in each hand at your sides.',
      'Step forward and lower until both knees reach 90 degrees.',
      'Push through the front foot and step into the next lunge.',
    ],
    tips: [
      'Your front knee should track over your foot, not past your toes.',
      'Take slightly longer steps to feel more glutes.',
    ],
  ),
  Exercise(
    id: 'bulgarianSplitSquat',
    name: 'Bulgarian Split Squat',
    group: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    isCompound: true,
    steps: [
      'Stand a big step in front of a bench, rear foot resting on it.',
      'Hold a dumbbell in each hand.',
      'Lower straight down until your front thigh is parallel.',
      'Drive up through the front foot. Finish the set, then switch legs.',
    ],
    tips: [
      'Everyone hates these because they work. Stick with them.',
      'Stay upright for quads, lean slightly forward for glutes.',
    ],
  ),
  Exercise(
    id: 'hipThrust',
    name: 'Barbell Hip Thrust',
    group: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    isCompound: true,
    steps: [
      'Sit with your upper back against a bench, bar over your hips.',
      'Plant your feet flat, shoulder width.',
      'Drive your hips up until your body is a straight line.',
      'Squeeze your glutes hard, then lower under control.',
    ],
    tips: [
      'Use a bar pad, your hip bones will thank you.',
      'Chin tucked, ribs down. Do not arch your lower back at the top.',
    ],
  ),
  Exercise(
    id: 'calfRaise',
    name: 'Standing Calf Raise',
    group: 'legs',
    equipment: 'machine',
    primaryMuscles: ['calves'],
    steps: [
      'Stand with the balls of your feet on the platform, heels hanging.',
      'Lower your heels for a deep stretch.',
      'Rise up onto your toes as high as possible.',
    ],
    tips: [
      'Pause two seconds in the stretch, no bouncing.',
      'Calves respond to full range and patience, not weight.',
    ],
  ),
  Exercise(
    id: 'seatedCalfRaise',
    name: 'Seated Calf Raise',
    group: 'legs',
    equipment: 'machine',
    primaryMuscles: ['calves'],
    steps: [
      'Sit with the pads on your knees, balls of feet on the platform.',
      'Lower your heels to a full stretch.',
      'Press up onto your toes and squeeze.',
    ],
    tips: [
      'The bent knee targets the deeper soleus muscle.',
      'Slow reps, full range, every time.',
    ],
  ),

  // ----- Core -----
  Exercise(
    id: 'plank',
    name: 'Plank',
    group: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'shoulders'],
    steps: [
      'Rest on your forearms and toes, elbows under shoulders.',
      'Form a straight line from head to heels.',
      'Hold while breathing steadily. Log the seconds you held as reps.',
    ],
    tips: [
      'Squeeze glutes and abs, do not let the hips sag or pike.',
      'A shorter, perfect hold beats a long, saggy one.',
    ],
  ),
  Exercise(
    id: 'sidePlank',
    name: 'Side Plank',
    group: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'shoulders'],
    steps: [
      'Lie on your side, propped on one forearm, elbow under shoulder.',
      'Lift your hips so your body forms a straight line.',
      'Hold, then switch sides. Log the seconds per side as reps.',
    ],
    tips: [
      'Push the floor away, do not hang on the shoulder.',
      'Stack your feet or stagger them for more balance.',
    ],
  ),
  Exercise(
    id: 'crunch',
    name: 'Crunch',
    group: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['abs'],
    steps: [
      'Lie on your back with knees bent, hands lightly behind your head.',
      'Curl your shoulder blades off the floor.',
      'Lower slowly without pulling on your neck.',
    ],
    tips: [
      'Exhale hard as you crunch up.',
      'Small range done well, this is not a sit-up.',
    ],
  ),
  Exercise(
    id: 'cableCrunch',
    name: 'Cable Crunch',
    group: 'core',
    equipment: 'cable',
    primaryMuscles: ['abs'],
    steps: [
      'Kneel below a high pulley holding the rope beside your head.',
      'Crunch your elbows toward your knees, rounding your spine.',
      'Return slowly until your abs are stretched.',
    ],
    tips: [
      'Your hips stay still, the abs curl the spine.',
      'The one ab exercise you can keep adding weight to.',
    ],
  ),
  Exercise(
    id: 'legRaise',
    name: 'Hanging Leg Raise',
    group: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'forearms'],
    steps: [
      'Hang from a pull-up bar with straight arms.',
      'Raise your legs until your thighs pass parallel.',
      'Lower slowly without swinging.',
    ],
    tips: [
      'Tilt your pelvis up at the top, do not just lift the legs.',
      'Too hard? Start with bent-knee raises.',
    ],
  ),
  Exercise(
    id: 'russianTwist',
    name: 'Russian Twist',
    group: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs'],
    steps: [
      'Sit with knees bent, leaning back until your abs engage.',
      'Hold a plate or dumbbell with both hands.',
      'Rotate the weight side to side, touching near each hip.',
    ],
    tips: [
      'Rotate from the ribs, not just the arms.',
      'Lift your feet off the floor to make it harder.',
    ],
  ),
  Exercise(
    id: 'abWheelRollout',
    name: 'Ab Wheel Rollout',
    group: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'lats', 'shoulders'],
    steps: [
      'Kneel holding the ab wheel under your shoulders.',
      'Roll forward as far as you can keep your back flat.',
      'Pull back to the start using your abs.',
    ],
    tips: [
      'Tuck your pelvis and squeeze your glutes before rolling.',
      'Only roll as far as you can control, range grows with strength.',
    ],
  ),
  Exercise(
    id: 'deadBug',
    name: 'Dead Bug',
    group: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['abs'],
    steps: [
      'Lie on your back, arms up, knees bent at 90 degrees over hips.',
      'Lower one arm and the opposite leg toward the floor.',
      'Return and repeat with the other pair.',
    ],
    tips: [
      'Press your lower back into the floor the entire time.',
      'Slow is the whole point. Two seconds out, two seconds back.',
    ],
  ),

  // ----- Cardio -----
  Exercise(
    id: 'treadmillRun',
    name: 'Treadmill Run',
    group: 'cardio',
    equipment: 'machine',
    primaryMuscles: ['quads', 'hamstrings', 'calves'],
    secondaryMuscles: ['glutes'],
    steps: [
      'Start walking, then raise the speed to an easy jog.',
      'Run tall with relaxed shoulders and a slight forward lean.',
      'Log minutes as reps.',
    ],
    tips: [
      'You should be able to speak in short sentences at an easy pace.',
      'A 1 percent incline mimics outdoor running.',
    ],
  ),
  Exercise(
    id: 'rowingMachine',
    name: 'Rowing Machine',
    group: 'cardio',
    equipment: 'machine',
    primaryMuscles: ['upperBack', 'lats', 'quads'],
    secondaryMuscles: ['biceps', 'hamstrings', 'abs'],
    steps: [
      'Strap in and grab the handle with straight arms.',
      'Drive with the legs first, then lean back, then pull to your chest.',
      'Reverse the order on the way forward: arms, body, legs.',
      'Log minutes as reps.',
    ],
    tips: [
      'Order matters: legs, back, arms. Most beginners pull arms first.',
      'Power comes from the legs, about 60 percent of every stroke.',
    ],
  ),
  Exercise(
    id: 'stationaryBike',
    name: 'Stationary Bike',
    group: 'cardio',
    equipment: 'machine',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['hamstrings', 'calves', 'glutes'],
    steps: [
      'Set the saddle so your knee stays slightly bent at the bottom.',
      'Pedal at a steady, conversational effort.',
      'Log minutes as reps.',
    ],
    tips: [
      'The easiest cardio on the joints, perfect for recovery days.',
      'Alternate 30 hard and 90 easy seconds for intervals.',
    ],
  ),
  Exercise(
    id: 'jumpRope',
    name: 'Jump Rope',
    group: 'cardio',
    equipment: 'bodyweight',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['quads', 'shoulders', 'forearms'],
    steps: [
      'Hold the handles at hip height, elbows close to your body.',
      'Jump just high enough to clear the rope, landing softly.',
      'Spin the rope from the wrists, not the arms.',
      'Log minutes as reps.',
    ],
    tips: [
      'Small, quick hops on the balls of your feet.',
      'Trip? Just keep going, rhythm comes within a week.',
    ],
  ),
  Exercise(
    id: 'burpee',
    name: 'Burpee',
    group: 'cardio',
    equipment: 'bodyweight',
    primaryMuscles: ['quads', 'chest'],
    secondaryMuscles: ['abs', 'shoulders', 'triceps'],
    steps: [
      'Squat down and place your hands on the floor.',
      'Kick your feet back to a push-up position and do a push-up.',
      'Jump your feet back in and leap straight up.',
    ],
    tips: [
      'Pace yourself, smooth reps beat frantic ones.',
      'Skip the push-up or the jump to scale it down.',
    ],
  ),
];

final Map<String, Exercise> _byId = {for (final e in exerciseLibrary) e.id: e};

Exercise exerciseById(String id) => _byId[id]!;

/// Stable filter-group keys in display order.
const List<String> exerciseGroups = [
  'chest',
  'back',
  'shoulders',
  'arms',
  'legs',
  'core',
  'cardio',
];
